export const UI_LABELS: Record<string, any> = {
  // --- Русский (RU) ---
  ru: {
    header: "Гороскоп",
    love: "Любовь",
    money: "Деньги",
    mood: "Настроение",
    advice: "Совет",
    affirmation: "Аффирмация дня",
    compatibility: "Совместимость",
    lucky_numbers: "Числа удачи",
    power_time: "Время силы",
    color: "Цвет успеха",
    tomorrow: "Взгляд в завтра",
    upgrade_text: "Хотите знать больше?",
    upgrade_btn: "Перейти на Premium",
    footer: "Ваш персональный астро-помощник",
    signs: {
      aries: "Овен ♈",
      taurus: "Телец ♉",
      gemini: "Близнецы ♊",
      cancer: "Рак ♋",
      leo: "Лев ♌",
      virgo: "Дева ♍",
      libra: "Весы ♎",
      scorpio: "Скорпион ♏",
      sagittarius: "Стрелец ♐",
      capricorn: "Козерог ♑",
      aquarius: "Водолей ♒",
      pisces: "Рыбы ♓",
    },
  },

  // --- Белорусский регион (BY) - используем русский язык ---
  by: {
    header: "Гороскоп",
    love: "Любовь",
    money: "Деньги",
    mood: "Настроение",
    advice: "Совет",
    affirmation: "Аффирмация дня",
    compatibility: "Совместимость",
    lucky_numbers: "Числа удачи",
    power_time: "Время силы",
    color: "Цвет успеха",
    tomorrow: "Взгляд в завтра",
    upgrade_text: "Хотите знать больше?",
    upgrade_btn: "Перейти на Premium",
    footer: "Ваш персональный астро-помощник",
    signs: {
      aries: "Овен ♈",
      taurus: "Телец ♉",
      gemini: "Близнецы ♊",
      cancer: "Рак ♋",
      leo: "Лев ♌",
      virgo: "Дева ♍",
      libra: "Весы ♎",
      scorpio: "Скорпион ♏",
      sagittarius: "Стрелец ♐",
      capricorn: "Козерог ♑",
      aquarius: "Водолей ♒",
      pisces: "Рыбы ♓",
    },
  },

  // --- Английский (EN) ---
  en: {
    header: "Daily Horoscope",
    love: "Love",
    money: "Money",
    mood: "Mood",
    advice: "Advice",
    affirmation: "Daily Affirmation",
    compatibility: "Compatibility",
    lucky_numbers: "Lucky Numbers",
    power_time: "Power Time",
    color: "Color",
    tomorrow: "Insight for Tomorrow",
    upgrade_text: "Want more insights?",
    upgrade_btn: "Get Premium",
    footer: "Your personal astro-guide",
    signs: {
      aries: "Aries ♈",
      taurus: "Taurus ♉",
      gemini: "Gemini ♊",
      cancer: "Cancer ♋",
      leo: "Leo ♌",
      virgo: "Virgo ♍",
      libra: "Libra ♎",
      scorpio: "Scorpio ♏",
      sagittarius: "Sagittarius ♐",
      capricorn: "Capricorn ♑",
      aquarius: "Aquarius ♒",
      pisces: "Pisces ♓",
    },
  },

  // --- Немецкий (DE) ---
  de: {
    header: "Tageshoroskop",
    love: "Liebe",
    money: "Finanzen",
    mood: "Stimmung",
    advice: "Ratschlag",
    affirmation: "Tagesaffirmation",
    compatibility: "Kompatibilität",
    lucky_numbers: "Glückszahlen",
    power_time: "Kraftvolle Zeit",
    color: "Erfolgsfarbe",
    tomorrow: "Ausblick auf morgen",
    upgrade_text: "Möchten Sie mehr erfahren?",
    upgrade_btn: "Premium entdecken",
    footer: "Ihr persönlicher Astro-Guide",
    signs: {
      aries: "Widder ♈",
      taurus: "Stier ♉",
      gemini: "Zwillinge ♊",
      cancer: "Krebs ♋",
      leo: "Löwe ♌",
      virgo: "Jungfrau ♍",
      libra: "Waage ♎",
      scorpio: "Skorpion ♏",
      sagittarius: "Schütze ♐",
      capricorn: "Steinbock ♑",
      aquarius: "Wassermann ♒",
      pisces: "Fische ♓",
    },
  },

  // --- Казахский (KZ) ---
  kk: {
    header: "Жұлдыз жорамал",
    love: "Махаббат",
    money: "Қаржы",
    mood: "Көңіл-күй",
    advice: "Кеңес",
    affirmation: "Күн аффирмациясы",
    compatibility: "Сәйкестік",
    lucky_numbers: "Сәтті сандар",
    power_time: "Қуатты уақыт",
    color: "Сәттілік түсі",
    tomorrow: "Ертеңгі болжам",
    upgrade_text: "Көбірек білгіңіз келе ме?",
    upgrade_btn: "Premium-ға өту",
    footer: "Сіздің жеке астро-көмекшіңіз",
    signs: {
      aries: "Тоқты ♈",
      taurus: "Торпақ ♉",
      gemini: "Егіздер ♊",
      cancer: "Шаян ♋",
      leo: "Арыстан ♌",
      virgo: "Бикеш ♍",
      libra: "Таразы ♎",
      scorpio: "Сарышаян ♏",
      sagittarius: "Мерген ♐",
      capricorn: "Тауешкі ♑",
      aquarius: "Суқұйғыш ♒",
      pisces: "Балықтар ♓",
    },
  },

  // --- Китайский (ZH) ---
  zh: {
    header: "每日运势",
    love: "爱情",
    money: "财富",
    mood: "心情",
    advice: "建议",
    affirmation: "每日正能量",
    compatibility: "星座配对",
    lucky_numbers: "幸运数字",
    power_time: "能量时刻",
    color: "幸运色",
    tomorrow: "明日展望",
    upgrade_text: "想了解更多吗？",
    upgrade_btn: "升级至高级版",
    footer: "您的专属星座助手",
    signs: {
      aries: "白羊座 ♈",
      taurus: "金牛座 ♉",
      gemini: "双子座 ♊",
      cancer: "巨蟹座 ♋",
      leo: "狮子座 ♌",
      virgo: "处女座 ♍",
      libra: "天秤座 ♎",
      scorpio: "天蝎座 ♏",
      sagittarius: "射手座 ♐",
      capricorn: "摩羯座 ♑",
      aquarius: "水瓶座 ♒",
      pisces: "双鱼座 ♓",
    },
  },
};
